Description:
    This template deploys an AWS security groups for the environment.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    VPCStackName:
        Description: The stackname for the VPC creation
        Type: String


Resources:

    DBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId:
              Fn::ImportValue:
                !Sub "${VPCStackName}-VPCID"

            GroupDescription: Enable PSQL access via port 5432
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: '5432'
                  ToPort: '5432'
                  CidrIp:
                      Fn::ImportValue:
                        !Sub "${VPCStackName}-VPCCidrBlock"
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName} RDS Security Group

    ECSSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId:
              Fn::ImportValue:
                !Sub "${VPCStackName}-VPCID"

            GroupDescription: Access to the ECS Instance
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: '8080'
                  ToPort: '8080'
                  CidrIp:
                      Fn::ImportValue:
                        !Sub "${VPCStackName}-VPCCidrBlock"
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName} ECS Security Group

    # LBSecurityGroup:
    #     Type: AWS::EC2::SecurityGroup
    #     Properties:
    #         VpcId:
    #           Fn::ImportValue:
    #             !Sub "${VPCStackName}-VPCID"
    #
    #         GroupDescription: Access to the ECS Instance
    #         SecurityGroupIngress:
    #             - IpProtocol: tcp
    #               FromPort: '80'
    #               ToPort: '80'
    #               CidrIp:
    #                   Fn::ImportValue:
    #                     !Sub "${VPCStackName}-VPCCidrBlock"
    #         Tags:
    #             - Key: Name
    #               Value: !Sub ${EnvironmentName} Load Balancer Security Group

Outputs:

    DBSecurityGroup:
        Description: A reference to the RDS Security Group
        Value: !Ref DBSecurityGroup
        Export:
            Name: !Sub "${AWS::StackName}-RDSSecurityGroup"

    ECSecurityGroup:
        Description: A reference to the ECS Security Group
        Value: !Ref ECSSecurityGroup
        Export:
            Name: !Sub "${AWS::StackName}-ECSSecurityGroup"

    # LBSecurityGroup:
    #     Description: A reference to the ECS Security Group
    #     Value: !Ref LBSecurityGroup
    #     Export:
    #         Name: !Sub "${AWS::StackName}-LBSecurityGroup"
